# Generated by Django 3.1 on 2020-11-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'تبلیغ کننده',
                'verbose_name_plural': 'تبلیغ کنندگان',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('views', models.PositiveBigIntegerField(default=0)),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('img_url', models.URLField(verbose_name='ادرس عکس تبلیغ')),
                ('link', models.URLField(verbose_name='ادرس سایت شما')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads',
                                                 to='advertiser_management.advertiser', verbose_name='تبلیغ کننده')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
            },
        ),
    ]
